name: test-my-project
on: push

jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '17'
      - run: make install
      - run: make lint
